#!/bin/sh
### BEGIN INIT INFO
# Provides: opensemanticsearch-filemonitoring
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Filemonitoring
# Description: Start indexing of new or changed files monitored by inotify.
### END INIT INFO
  
start () {
    echo -n "Starting opensemanticsearch_filemonitoring daemon..."

    daemon --respawn --command "/usr/bin/opensemanticsearch-filemonitoring --fromfile /etc/opensemanticsearch/filemonitoring/files" --name=opensemanticsearch-filemonitoring --verbose
    RETVAL=$?
    if [ $RETVAL = 0 ]
    then
        echo "done."
    else
        echo "failed. See error code for more information."
    fi
    return $RETVAL
}
 
stop () {
    # Stop daemon
    echo -n "Stopping opensemanticsearch-filemonitoring daemon..."
 
    daemon --stop --name=opensemanticsearch-filemonitoring --verbose
    RETVAL=$?
 
    if [ $RETVAL = 0 ]
    then
        echo "Done."
    else
        echo "Failed. See error code for more information."
    fi
    return $RETVAL
}
 
restart () {
    daemon --restart --name=opensemanticsearch-filemonitoring --verbose
}
 
status () {
    # Report on the status of the daemon
    daemon --running --verbose --name=opensemanticsearch-filemonitoring
    return $?
}
 
case "$1" in
    start)
        start
    ;;
    status)
        status
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    *)
        echo $"Usage: opensemanticsearch-filemonitoring {start|status|stop|restart}"
        exit 3
    ;;
esac
 
exit $RETVAL
