#!/bin/sh

adduser --system --disabled-password opensemanticetl

# install Scrapy
pip3 install scrapy

# install py2neo
pip3 install py2neo==3.1.2

# install warcio
pip3 install warcio

# rights for thumbnail dir
chown opensemanticetl /var/opensemanticsearch/thumbnails
chmod o+w /var/opensemanticsearch/thumbnails

# load our additional systemd service config
systemctl daemon-reload

# start while booting
systemctl enable opensemanticetl
systemctl enable opensemanticetl-filemonitoring

# (re)start after installation (or upgrade)
systemctl restart opensemanticetl
